### ISSUE TITLE
Yoast SEO conflict: product server side rich snippets aggregates all product reviews instead of a single product review

### ISSUE THREAD

**Issue by JethroHazelhurst** [Reviewscouk/WooCommercePlugin#60]
### Issue:

This product only has 41 reviews, yet the aggregateReview figure is the sum of all our product reviews across the entire catalog - 5,376 reviews.

<img width="520" alt="image" src="https://github.com/user-attachments/assets/4e93690c-322f-4775-895c-8ba5a3870587">

In the [REVIEWS.io](http://reviews.io/) plugin, under “Rich Snippets” when `Enable Product Rich Snippet` is set to `Yes` and `Server Side Rich Snippets` is set to `Yes` the product schema that is generated show an aggregate of all our product reviews across the entire catalogue in REVIEWS.io:

![image](https://github.com/user-attachments/assets/9a99af54-75f4-4cf4-9db4-4b61311f01d6)

When setting either the first option `Enable Product Rich Snippet` to `No` or both options to `No` only the Yoast SEO schema is displayed with no aggregateRating or product reviews:

![image](https://github.com/user-attachments/assets/e22ea0a0-163f-48c9-99e1-9f08b30e1fde)

When setting `Enable Product Rich Snippet` to `Yes` and `Server Side Rich Snippets` to `No` the functionality works as intended:

![image](https://github.com/user-attachments/assets/b124cb1c-ff67-457d-b577-42829a21c73b)

However we would prefer the option `Server Side Rich Snippets` worked as intended and we were able to render our schema on the serverside rather than being forced to render it client side with a javascript widget.

**Comment by rahaddon** [comment]
Wordpress escaping function was encoding HTML entities in product SKUs sent on the richsnippet request causing the URL query parameters to become malformed and not readable by the endpoint. 

Update pushed in version 1.3.4 should resolve this issue. Please let me know if you experience any further issues and I'll get them resolved as soon as possible. Thanks!
